"""Reprolith — auto-reproduction & certification engine for the biomedical modeling literature.

This is the engine skeleton: the domain shapes a certificate is built from, the rule
that derives its verdict, the inescapable scope statement, and the determinism harness
that makes a certificate byte-reproducible. The ingestion, reconstruction, and
simulation-oracle stages described in ``openspec/`` build on top of these shapes.
"""

from __future__ import annotations

from .agreement import AgreementReport, EntryAgreement, build_agreement_report
from .canonical import canonical_bytes, canonical_json, content_hash
from .catalog import (
    BlindEntry,
    Catalog,
    CatalogEntry,
    GroundTruth,
    Identifiers,
    IllegalTransition,
    Transition,
)
from .certificate import build_certificate, derive_overall
from .certify import (
    Claim,
    CurveClaim,
    EstimationClaim,
    PopulationClaim,
    certify_curves,
    certify_estimation,
    certify_model,
    certify_population,
)
from .constraint_based import (
    certify_constraint_based,
    constraint_based_dossier,
    validate_constraint_based,
)
from .corroboration import EngineCorroboration, corroborate_curve
from .determinism import certificate_digest, same_modulo_run_metadata
from .dossier import (
    Dossier,
    DossierClaim,
    Equation,
    ExtractionConfidence,
    Gap,
    GapKind,
    ModelArtifact,
    Parameter,
    estimate_difficulty,
)
from .engine import (
    EngineUnavailable,
    NonFiniteSimulation,
    engine_pin,
    engine_version,
    roadrunner_pin,
    roadrunner_version,
    simulate,
    simulate_with_roadrunner,
)
from .enums import (
    LifecycleState,
    ModelClass,
    OverallVerdict,
    ReproductionLevel,
    Verdict,
)
from .fba import (
    FbaModel,
    FbaUnavailable,
    FrogComparison,
    FrogFingerprint,
    InfeasibleFba,
    compare_frog,
    essentiality_agreement,
    flux_variability,
    frog_fingerprint,
    gene_essentiality,
    judge_fingerprint,
    judge_flux,
    judge_objective,
    reaction_essentiality,
    solve_objective,
)
from .ingest import ingest_sbml
from .linter import (
    LintResult,
    lint_curve,
    lint_distribution,
    lint_estimation,
    lint_objective,
    lint_steady_state,
)
from .logical import (
    BooleanNetwork,
    LogicalClaim,
    UpdateScheme,
    certify_logical,
    compile_boolean_rule,
    judge_attractor_set,
    judge_steady_state,
    parse_boolean_network,
)
from .mcp_server import handle_request, serve_stdio
from .model import (
    Assumption,
    Certificate,
    ClaimAssessment,
    EnginePin,
    PaperIdentity,
    RunMetadata,
)
from .oracle import (
    Attribution,
    ComparisonMethod,
    FailureMode,
    Fault,
    PercentileBand,
    ReferenceKind,
    Tolerance,
    ToleranceSource,
    assess_match,
    band_envelope_distance,
    default_tolerance,
    estimation_default_tolerance,
    judge_curve,
    judge_distribution,
    judge_estimation,
    judge_scalar,
    normalized_curve_distance,
    not_evaluable,
    relative_error,
    verdict_for,
)
from .persistence import (
    bundle_from_dict,
    certificate_from_content,
    dossier_from_dict,
)
from .presubmission import presubmission_report, render_presubmission_human
from .query import ReprolithQuery
from .reconstruction import (
    ModelOrigin,
    NonReconstructable,
    RecipeStep,
    ReconstructionBundle,
    close_gap,
)
from .render import (
    claim_counts,
    gap_items,
    render_badge,
    render_human,
    render_machine,
    render_registry,
)
from .revision import DossierHistory, DossierRevision, dossier_digest, revise
from .run import (
    advance_to_outcome,
    blocked_certificate,
    certified_from_claims,
    load_claims_dataset,
    run_test_set,
)
from .sbml import (
    build_model_sbml,
    compare_sbml_to_dossier,
    ingest_fbc_sbml,
    ingest_qual_sbml,
)
from .scope import Scope
from .screening import Candidate, Screening, ScreeningResult, screen_candidate, storable_content
from .sedml import SimulationRecipe, parse_sedml_recipes
from .seed import SeedingReport, load_test_set, seed_candidates, seed_catalog
from .spatial import diffuse_1d, gaussian_profile
from .stochastic import (
    Reaction,
    StochasticClaim,
    certify_stochastic,
    ensemble_final_counts,
    ensemble_percentile_bands,
    gillespie,
    gillespie_at_times,
    species_mean_variance,
)
from .supersession import CertificateLedger, describe_changes
from .verification import (
    VerificationDecision,
    VerificationItem,
    VerificationQueue,
    certificates_needing_review,
    reverify_dependents,
)

__version__ = "0.0.1"

__all__ = [
    "AgreementReport",
    "Assumption",
    "Attribution",
    "BooleanNetwork",
    "BlindEntry",
    "Candidate",
    "EntryAgreement",
    "Catalog",
    "CatalogEntry",
    "CertificateLedger",
    "Certificate",
    "Claim",
    "ClaimAssessment",
    "CurveClaim",
    "ComparisonMethod",
    "Dossier",
    "EstimationClaim",
    "DossierClaim",
    "DossierHistory",
    "DossierRevision",
    "EngineCorroboration",
    "EnginePin",
    "EngineUnavailable",
    "Equation",
    "ExtractionConfidence",
    "Fault",
    "FbaModel",
    "FbaUnavailable",
    "FrogComparison",
    "FrogFingerprint",
    "InfeasibleFba",
    "FailureMode",
    "Gap",
    "GapKind",
    "GroundTruth",
    "Identifiers",
    "IllegalTransition",
    "LifecycleState",
    "LintResult",
    "LogicalClaim",
    "ModelArtifact",
    "ModelClass",
    "ModelOrigin",
    "NonFiniteSimulation",
    "NonReconstructable",
    "OverallVerdict",
    "Parameter",
    "PaperIdentity",
    "PercentileBand",
    "PopulationClaim",
    "Reaction",
    "RecipeStep",
    "StochasticClaim",
    "ReconstructionBundle",
    "ReferenceKind",
    "ReproductionLevel",
    "ReprolithQuery",
    "RunMetadata",
    "Scope",
    "Screening",
    "ScreeningResult",
    "SeedingReport",
    "SimulationRecipe",
    "Tolerance",
    "ToleranceSource",
    "Transition",
    "UpdateScheme",
    "Verdict",
    "VerificationDecision",
    "VerificationItem",
    "VerificationQueue",
    "advance_to_outcome",
    "blocked_certificate",
    "build_agreement_report",
    "build_certificate",
    "build_model_sbml",
    "bundle_from_dict",
    "canonical_bytes",
    "canonical_json",
    "certificate_digest",
    "certificate_from_content",
    "certificates_needing_review",
    "certified_from_claims",
    "certify_constraint_based",
    "certify_curves",
    "certify_estimation",
    "certify_model",
    "certify_logical",
    "certify_population",
    "certify_stochastic",
    "claim_counts",
    "constraint_based_dossier",
    "close_gap",
    "corroborate_curve",
    "assess_match",
    "band_envelope_distance",
    "compare_frog",
    "compare_sbml_to_dossier",
    "compile_boolean_rule",
    "content_hash",
    "default_tolerance",
    "estimation_default_tolerance",
    "derive_overall",
    "describe_changes",
    "diffuse_1d",
    "dossier_digest",
    "dossier_from_dict",
    "engine_pin",
    "estimate_difficulty",
    "engine_version",
    "ensemble_final_counts",
    "ensemble_percentile_bands",
    "essentiality_agreement",
    "flux_variability",
    "frog_fingerprint",
    "gaussian_profile",
    "gene_essentiality",
    "gap_items",
    "gillespie",
    "gillespie_at_times",
    "handle_request",
    "ingest_fbc_sbml",
    "ingest_qual_sbml",
    "ingest_sbml",
    "judge_attractor_set",
    "judge_curve",
    "judge_distribution",
    "judge_estimation",
    "judge_fingerprint",
    "judge_flux",
    "judge_objective",
    "judge_scalar",
    "judge_steady_state",
    "lint_curve",
    "lint_distribution",
    "lint_estimation",
    "lint_objective",
    "lint_steady_state",
    "load_claims_dataset",
    "load_test_set",
    "normalized_curve_distance",
    "not_evaluable",
    "parse_boolean_network",
    "parse_sedml_recipes",
    "presubmission_report",
    "relative_error",
    "render_badge",
    "render_human",
    "render_machine",
    "render_presubmission_human",
    "render_registry",
    "reverify_dependents",
    "revise",
    "roadrunner_pin",
    "roadrunner_version",
    "run_test_set",
    "screen_candidate",
    "seed_candidates",
    "simulate_with_roadrunner",
    "storable_content",
    "same_modulo_run_metadata",
    "serve_stdio",
    "seed_catalog",
    "simulate",
    "reaction_essentiality",
    "solve_objective",
    "species_mean_variance",
    "validate_constraint_based",
    "verdict_for",
    "__version__",
]
