"""The committed reference values, checked against the paper they are read from.

Every other reference value in this repository is computed by an independent tool — COBRApy,
libRoadRunner, CANA — or by closed-form mathematics, and each of those is checked against its
generator. The two metformin plasma Cmax values are the exception: the only numbers here that
come from a *manuscript*, and the single thing the README's "one checks a reconstruction against
numbers read from a paper" rests on. Nothing checked them against the paper.

One of them was wrong. The 500 mg plasma Cmax was recorded as 6.2 nmol/mL and cited to Table 4;
the paper prints **6.1**, in Table 6, in Table 4's own `Fitted` row, and in the sentence of its
Results. 6.2 appears nowhere in it. Both claims also cited the wrong place: Table 4 is the
comparison against *measured* data (5.7 and 12.9 nmol/mL), and the values the claims target are
the paper's own simulation, which is Table 6.

`datasets/manuscripts/` holds the cited rows, quoted from the open-access article under CC BY 4.0
and regenerated by `scripts/fetch_manuscript_tables.py`. This test reads only that file — no
network, so it runs in the dependency-free core gate.
"""

from __future__ import annotations

import json
from pathlib import Path

_ROOT = Path(__file__).parent.parent
_CLAIMS = json.loads((_ROOT / "datasets" / "pkpd_claims.json").read_text(encoding="utf-8"))
_TABLES = json.loads(
    (_ROOT / "datasets" / "manuscripts" / "BIOMD0000001028_tables.json").read_text(encoding="utf-8")
)


def _plasma_cmax(dose: str) -> str:
    """The plasma Cmax the paper's Table 6 prints for a single oral dose, as it is printed."""
    rows = _TABLES["tables"]["Table 6"]["rows"]
    header = rows[0]
    cmax = header.index("Cmax, nmol/mL")
    # The first body row carries the tissue name and the rest continue it, so the dose is the
    # cell before the numbers on the first and the first cell after that.
    for row in rows[1:]:
        cells = row[1:] if row[0] == "Plasma" else row
        if cells[0] == dose:
            return cells[cmax - 1]
    raise AssertionError(f"Table 6 has no plasma row for {dose} mg")


def test_each_metformin_claim_states_the_number_the_paper_prints() -> None:
    claims = {c["claim_id"]: c for c in _CLAIMS["entries"]["BIOMD0000001028"]["claims"]}
    assert float(_plasma_cmax("500")) == claims["Cmax-500mg"]["reported"]
    assert float(_plasma_cmax("1000")) == claims["Cmax-1000mg"]["reported"]


def test_each_claim_cites_the_table_its_number_is_actually_in() -> None:
    """Both used to cite Table 4, which prints different numbers for the same two doses."""
    claims = {c["claim_id"]: c for c in _CLAIMS["entries"]["BIOMD0000001028"]["claims"]}
    for claim in claims.values():
        assert "Table 6" in claim["source_location"], claim["source_location"]


def test_the_measured_values_are_a_different_number_and_are_not_what_is_claimed() -> None:
    """The check above would pass on a coincidence if the two tables agreed. They do not.

    Table 4 is the comparison against measured data — 5.7 nmol/mL at 500 mg, 12.9 at 1000 — and
    reproducing an experiment is not what a certificate attests to. If a later edit points these
    claims back at measured values, the numbers move and this fails.
    """
    rows = _TABLES["tables"]["Table 4"]["rows"]
    measured = {
        row[0]: row[3] for row in rows if row and row[0] in ("Zaharenko, 500mg", "Chung 1000mg")
    }
    assert measured == {"Zaharenko, 500mg": "5.7", "Chung 1000mg": "12.9"}
    reported = {
        c["reported"] for c in _CLAIMS["entries"]["BIOMD0000001028"]["claims"]
    }
    assert reported.isdisjoint({5.7, 12.9})


def test_the_quoted_rows_carry_the_papers_licence_and_identity() -> None:
    """Redistributed content, so its terms travel with it (datasets/THIRD-PARTY-NOTICES.md)."""
    paper = _TABLES["paper"]
    assert paper["doi"] == "10.1371/journal.pone.0249594"
    assert "CC BY 4.0" in paper["license"]
    assert paper["pmcid"].startswith("PMC")
